"""updated db columns

Revision ID: 8c62441e60ff
Revises: 49feb903a002
Create Date: 2021-06-25 14:22:43.787996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c62441e60ff'
down_revision = '49feb903a002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('comics_appeared_in', sa.Integer(), nullable=True))
    op.add_column('hero', sa.Column('super_power', sa.String(length=150), nullable=True))
    op.add_column('hero', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.drop_column('hero', 'cost_of_prod')
    op.drop_column('hero', 'flight_time')
    op.drop_column('hero', 'camera_quality')
    op.drop_column('hero', 'price')
    op.drop_column('hero', 'dimensions')
    op.drop_column('hero', 'weight')
    op.drop_column('hero', 'max_speed')
    op.drop_column('hero', 'series')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('series', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('hero', sa.Column('max_speed', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('hero', sa.Column('weight', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('hero', sa.Column('dimensions', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('hero', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('hero', sa.Column('camera_quality', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('hero', sa.Column('flight_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('hero', sa.Column('cost_of_prod', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('hero', 'date_created')
    op.drop_column('hero', 'super_power')
    op.drop_column('hero', 'comics_appeared_in')
    # ### end Alembic commands ###
